name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  push-to-registry:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract meta information for auth
        id: meta-auth
        uses: docker/metadata-action@v3
        with:
          images: sadi001/hotel-booking-auth

      - name: Build and push auth
        uses: docker/build-push-action@v3
        with:
          context: ./services/auth
          file: ./services/auth/Dockerfile
          push: true
          tags: ${{ steps.meta-auth.outputs.tags }}

      - name: Extract meta information for booking-management
        id: meta-booking-management
        uses: docker/metadata-action@v3
        with:
          images: sadi001/hotel-booking-booking-management

      - name: Build and push booking-management
        uses: docker/build-push-action@v3
        with:
          context: ./services/booking-management
          file: ./services/booking-management/Dockerfile
          push: true
          tags: ${{ steps.meta-booking-management.outputs.tags }}

      - name: Extract meta information for user
        id: meta-user
        uses: docker/metadata-action@v3
        with:
          images: sadi001/hotel-booking-user

      - name: Build and push user
        uses: docker/build-push-action@v3
        with:
          context: ./services/user
          file: ./services/user/Dockerfile
          push: true
          tags: ${{ steps.meta-user.outputs.tags }}

      - name: Extract meta information for room
        id: meta-room
        uses: docker/metadata-action@v3
        with:
          images: sadi001/hotel-booking-room

      - name: Build and push room
        uses: docker/build-push-action@v3
        with:
          context: ./services/room
          file: ./services/room/Dockerfile
          push: true
          tags: ${{ steps.meta-room.outputs.tags }}

      - name: Extract meta information for hotel
        id: meta-hotel
        uses: docker/metadata-action@v3
        with:
          images: sadi001/hotel-booking-hotel

      - name: Build and push hotel
        uses: docker/build-push-action@v3
        with:
          context: ./services/hotel
          file: ./services/hotel/Dockerfile
          push: true
          tags: ${{ steps.meta-hotel.outputs.tags }}

      - name: Extract meta information for email
        id: meta-email
        uses: docker/metadata-action@v3
        with:
          images: sadi001/hotel-booking-email

      - name: Build and push email
        uses: docker/build-push-action@v3
        with:
          context: ./services/email
          file: ./services/email/Dockerfile
          push: true
          tags: ${{ steps.meta-email.outputs.tags }}
